# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  #- package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
  #  directory: "/apps/lifesaving-results"
    # Check the npm registry for updates every day (weekdays)
  #  schedule:
  #    interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "maven"
  # Look for a `Dockerfile` in the `root` directory
    directory: "/services"
  # Check for updates once a week
    schedule:
      interval: "weekly"
