version: "3.5"

services:
  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    restart: unless-stopped
    ports:
      - ${KEYCLOAK_PORT}:8080
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_STATISTICS=all
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
      - DB_SCHEMA=public
    networks:
      - internal
    depends_on:
      - keycloak-postgres
    volumes:
      - ./.keycloak/imports:/opt/jboss/keycloak/imports/

  keycloak-postgres:
    image: postgres
    container_name: keycloak-postgres
    restart: unless-stopped
    ports:
      - 48081:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  postgres:
