spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/competitions
    username: sa
    password: sa

app:
  development:
    test-ui-enabled: true

logging:
  level:
    org.springframework.security: DEBUG
