name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Adoptium
          java-version: 21
      - run: |
          cd ./services
          mvn -B verify --file pom.xml
